# Generated by Django 5.1.15 on 2026-09-22 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelehealthRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('manual', 'Manual Link'), ('zoom', 'Zoom'), ('daily', 'Daily'), ('twilio', 'Twilio')], default='manual', max_length=20)),
                ('join_url', models.URLField()),
                ('host_url', models.URLField(blank=True)),
                ('external_room_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telehealth_room', to='appointments.appointment')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telehealth_rooms', to='practices.practice')),
            ],
        ),
    ]
