# Generated by Django 5.1.15 on 2026-09-23 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('billing', '0001_initial'),
        ('clients', '0002_rename_emergyency_contact_name_client_emergency_contact_name_and_more'),
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sessions_purchased', models.PositiveIntegerField()),
                ('sessions_used', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='active', max_length=20)),
                ('purchased_at', models.DateField()),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to='clients.client')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to='practices.practice')),
            ],
            options={
                'ordering': ['-purchased_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('used_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_usage', to='appointments.appointment')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='billing.servicepackage')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.servicepackage'),
        ),
    ]
