# Generated by Django 5.1.15 on 2026-09-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_servicepackage_packageusage_invoice_package'),
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPackageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sessions_included', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_package_templates', to='practices.practice')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_packages', to='billing.sessionpackagetemplate'),
        ),
        migrations.AddConstraint(
            model_name='sessionpackagetemplate',
            constraint=models.UniqueConstraint(fields=('practice', 'name'), name='unique_session_package_template_per_practice'),
        ),
    ]
