# Generated by Django 5.1.15 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('billing', '0006_alter_practicesubscription_status')]

    operations = [
        migrations.AddField(
            model_name='packageusage',
            name='charge_reason',
            field=models.CharField(choices=[('completed', 'Completed session'), ('no_show', 'Approved no-show charge')], default='completed', max_length=20),
        ),
    ]
