# Generated by Django 5.2.17 on 2026-10-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoice_publishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesubscription',
            name='payment_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
