# Generated by Django 5.2.17 on 2026-10-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_practicesubscription_payment_failed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesubscription',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
