# Generated by Django 5.2.17 on 2026-10-06 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_profile_photo'),
        ('clinical', '0003_sessionnote_treatment_plan_progress'),
        ('practices', '0007_practice_stripe_connect_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='practices.practice'),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_notes', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_notes', to='practices.practice'),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_notes', to='practices.therapistprofile'),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='treatment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_notes', to='clinical.treatmentplan'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='practices.practice'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='practices.therapistprofile'),
        ),
    ]
