# Generated by Django 5.1.15 on 2026-09-28 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_practiceworkinghour'),
        ('clients', '0002_rename_emergyency_contact_name_client_emergency_contact_name_and_more'),
        ('portal', '0006_clientportalrequest_appointment'),
        ('practices', '0006_practice_public_booking_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('requested_starts_at', models.DateTimeField()),
                ('requested_ends_at', models.DateTimeField()),
                ('appointment_type', models.CharField(choices=[('in_person', 'In Person'), ('video', 'Video Call'), ('phone', 'Phone Call')], default='video', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_booking_requests', to='appointments.appointment')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_booking_requests', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_booking_requests', to='clients.client')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_booking_requests', to='practices.practice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
