# Generated by Django 5.1.15 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('portal', '0008_portalconversation_portalmessage')]

    operations = [
        migrations.AddField(
            model_name='portalmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
