# Generated by Django 5.2.17 on 2026-10-06 09:58

from django.db import migrations, models


def snapshot_existing_packets(apps, schema_editor):
    Assignment = apps.get_model('portal', 'ClientIntakeAssignment')
    for assignment in Assignment.objects.using(schema_editor.connection.alias).select_related('template').iterator(chunk_size=500):
        questions = assignment.template.questions
        keys = list(assignment.answers)
        if keys and all(key.startswith('question_') and key[9:].isdigit() for key in keys):
            keys.sort(key=lambda key: int(key[9:]))
        if keys and assignment.status != 'assigned':
            questions = []
            for key in keys:
                item = assignment.answers[key]
                label = key.replace('_', ' ').capitalize()
                questions.append(item.get('question', label) if isinstance(item, dict) else label)
        Assignment.objects.using(schema_editor.connection.alias).filter(pk=assignment.pk).update(template_snapshot={
            'name': assignment.template.name, 'description': assignment.template.description, 'questions': questions,
            'answer_keys': keys,
        })


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_clientportalrequest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintakeassignment',
            name='template_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(snapshot_existing_packets, migrations.RunPython.noop),
    ]
