# Generated by Django 5.1.15 on 2026-09-28 19:51

from django.db import migrations, models
from django.utils.text import slugify


def populate_public_booking_slugs(apps, schema_editor):
    Practice = apps.get_model('practices', 'Practice')
    used = set(Practice.objects.exclude(public_booking_slug='').values_list('public_booking_slug', flat=True))
    for practice in Practice.objects.order_by('id'):
        if practice.public_booking_slug:
            continue
        base = slugify(practice.name)[:140] or 'practice'
        slug = base
        suffix = 2
        while slug in used:
            slug = f'{base}-{suffix}'
            suffix += 1
        practice.public_booking_slug = slug
        practice.save(update_fields=['public_booking_slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0005_encrypt_externalintegration_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='public_booking_slug',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.RunPython(populate_public_booking_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='practice',
            name='public_booking_slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
