# Generated by Django 5.1.15 on 2026-09-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0006_practice_public_booking_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='practice',
            name='stripe_connect_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practice',
            name='stripe_connect_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practice',
            name='stripe_connect_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
