# Generated by Django 5.2.17 on 2026-10-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0007_practice_stripe_connect_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='subscription_required',
            field=models.BooleanField(default=False),
        ),
    ]
