# Generated by Django 5.2.17 on 2026-10-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0008_practice_subscription_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='free_trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='free_trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
