# Generated by Django 5.2.17 on 2026-10-09 11:52

import django.db.models.deletion
from django.db import migrations, models


def seed_slots(apps, schema_editor):
    from django.utils import timezone
    Invitation = apps.get_model('practices', 'EarlyAccessInvitation')
    Invitation.objects.bulk_create([
        Invitation(slot=slot, email='', token_hash=f'unissued-{slot}', expires_at=timezone.now())
        for slot in range(1, 11)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0009_practice_free_trial_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='free_access_kind',
            field=models.CharField(default='trial', max_length=20),
        ),
        migrations.CreateModel(
            name='EarlyAccessInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('practice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practices.practice')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('slot__gte', 1), ('slot__lte', 10)), name='early_access_ten_slots')],
            },
        ),
        migrations.RunPython(seed_slots, migrations.RunPython.noop),
    ]
