# Generated by Django 5.1.15 on 2026-09-17 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archive')], default='active', max_length=20)),
                ('ensurance_provider', models.CharField(blank=True, max_length=140)),
                ('ensurance_member_id', models.CharField(blank=True, max_length=80)),
                ('emergyency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergyency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=140)),
                ('address_line2', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='practices.practice')),
                ('primary_therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_clients', to='practices.therapistprofile')),
            ],
            options={
                'verbose_name': 'Client',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
