# Generated by Django 5.1.15 on 2026-09-17 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='emergyency_contact_name',
            new_name='emergency_contact_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='emergyency_contact_phone',
            new_name='emergency_contact_phone',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='ensurance_member_id',
            new_name='insurance_member_id',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='ensurance_provider',
            new_name='insurance_provider',
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_clients', to='practices.therapistprofile'),
        ),
    ]
