# Generated by Django 5.1.15 on 2026-09-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_emergyency_contact_name_client_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='client-photos/'),
        ),
    ]
