"""Disposable PostgreSQL integration test for provisioning, runtime access and restore."""
import os
import secrets
import subprocess
import sys
import uuid

import psycopg
from psycopg import sql
from ops.postgres_roles import provision, grant_runtime, verify_runtime


def main():
    env = dict(os.environ)
    suffix = uuid.uuid4().hex[:12]
    database, restored = 'nuviamy_roles_' + suffix, 'nuviamy_restore_' + suffix
    app, migration = 'app_' + suffix, 'migration_' + suffix
    app_password, migration_password = secrets.token_urlsafe(40), secrets.token_urlsafe(40)
    connection_args = dict(host=env['POSTGRES_HOST'], port=env.get('POSTGRES_PORT', '5432'), dbname=env['POSTGRES_DB'], user=env['POSTGRES_USER'], password=env['POSTGRES_PASSWORD'], autocommit=True)
    container = env['POSTGRES_CONTAINER']
    with psycopg.connect(**connection_args) as admin:
        try:
            admin.execute(sql.SQL('CREATE DATABASE {}').format(sql.Identifier(database)))
            with psycopg.connect(**dict(connection_args, dbname=database)) as owner:
                provision(owner, app, migration, app_password, migration_password)
            migration_env = dict(env, POSTGRES_DB=database, POSTGRES_USER=migration, POSTGRES_PASSWORD=migration_password)
            subprocess.run([sys.executable, 'manage.py', 'migrate', '--noinput'], env=migration_env, stdout=subprocess.DEVNULL, check=True)
            with psycopg.connect(**dict(connection_args, dbname=database, user=migration, password=migration_password)) as owner:
                grant_runtime(owner, app, migration)
                owner.execute('CREATE TABLE public.future_migration_fixture (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, value text)')
            with psycopg.connect(**dict(connection_args, dbname=database)) as owner:
                try:
                    verify_runtime(owner)
                except ValueError:
                    pass
                else:
                    raise AssertionError('Administrative runtime role was accepted')
                owner.execute(sql.SQL('GRANT UPDATE ON audit_auditlog TO {}').format(sql.Identifier(app)))
                with psycopg.connect(**dict(connection_args, dbname=database, user=app, password=app_password)) as runtime:
                    try:
                        verify_runtime(runtime)
                    except ValueError:
                        pass
                    else:
                        raise AssertionError('Excessive audit privileges were accepted')
                grant_runtime(owner, app, migration)
                owner.execute('ALTER TABLE clinical_sessionnote DISABLE TRIGGER clinical_protect_finalized')
                with psycopg.connect(**dict(connection_args, dbname=database, user=app, password=app_password)) as runtime:
                    try:
                        verify_runtime(runtime)
                    except ValueError:
                        pass
                    else:
                        raise AssertionError('Disabled clinical guard was accepted')
                owner.execute('ALTER TABLE clinical_sessionnote ENABLE TRIGGER clinical_protect_finalized')
            with psycopg.connect(**dict(connection_args, dbname=database, user=app, password=app_password)) as runtime:
                verify_runtime(runtime)
                runtime.execute("INSERT INTO future_migration_fixture (value) VALUES ('Synthetic migration defaults')")
                for statement in [
                    'ALTER TABLE audit_auditlog DISABLE TRIGGER audit_reject_mutation',
                    'ALTER TABLE clinical_sessionnote DISABLE TRIGGER clinical_protect_finalized',
                    'TRUNCATE auth_user CASCADE',
                    'DELETE FROM audit_auditlog',
                    "UPDATE audit_auditlog SET metadata='{}'",
                    'CREATE TABLE public.forbidden_fixture (id int)',
                    'CREATE TEMP TABLE forbidden_fixture (id int)',
                    'CREATE ROLE forbidden_fixture',
                    'SET session_replication_role=replica',
                    'SET ROLE ' + migration,
                    "CREATE OR REPLACE FUNCTION public.nuviamy_reject_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$",
                    "SELECT setval('future_migration_fixture_id_seq', 1)",
                    "DELETE FROM django_migrations",
                ]:
                    try:
                        with runtime.transaction():
                            runtime.execute(statement)
                    except psycopg.errors.InsufficientPrivilege:
                        pass
                    else:
                        raise AssertionError('Forbidden runtime operation unexpectedly succeeded: ' + statement)
            runtime_env = dict(env, POSTGRES_DB=database, POSTGRES_USER=app, POSTGRES_PASSWORD=app_password, DJANGO_MFA_REQUIRED='false', DJANGO_ALLOWED_HOSTS='testserver', FIELD_ENCRYPTION_KEY='MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA=')
            subprocess.run([sys.executable, 'manage.py', 'shell'], env=runtime_env, input=RUNTIME_SMOKE, text=True, check=True)
            # Administrative backups remain usable after ownership/grant separation.
            dump = subprocess.run(['docker', 'exec', container, 'pg_dump', '-U', env['POSTGRES_USER'], '-d', database, '-Fc'], stdout=subprocess.PIPE, check=True).stdout
            admin.execute(sql.SQL('CREATE DATABASE {}').format(sql.Identifier(restored)))
            subprocess.run(['docker', 'exec', '-i', container, 'pg_restore', '-U', env['POSTGRES_USER'], '-d', restored, '--no-owner', '--no-privileges', '--exit-on-error'], input=dump, check=True)
            with psycopg.connect(**dict(connection_args, dbname=restored)) as owner:
                provision(owner, app, migration, app_password, migration_password)
            with psycopg.connect(**dict(connection_args, dbname=restored, user=app, password=app_password)) as runtime:
                verify_runtime(runtime)
                assert runtime.execute("SELECT actor_username_snapshot FROM audit_auditlog WHERE object_type='synthetic.RoleFixture'").fetchone()[0] == 'synthetic-role-user'
                assert runtime.execute('SELECT is_locked FROM clinical_sessionnote').fetchone()[0]
            print('PostgreSQL role separation, denied administrative operations, runtime flows, future grants and backup/restore passed.')
        finally:
            for name in (database, restored):
                admin.execute('SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=%s AND pid<>pg_backend_pid()', [name])
                admin.execute(sql.SQL('DROP DATABASE IF EXISTS {}').format(sql.Identifier(name)))
            for name in (app, migration):
                admin.execute(sql.SQL('DROP ROLE IF EXISTS {}').format(sql.Identifier(name)))


RUNTIME_SMOKE = '''
from django.contrib.auth import get_user_model
from django.db import connection, transaction, IntegrityError
from django.test import Client as Browser
from apps.accounts.models import UserProfile
from apps.audit.models import AuditLog
from apps.clinical.models import SessionNote
from apps.clients.models import Client
from apps.practices.models import Practice, TherapistProfile
u = get_user_model().objects.create_user('synthetic-role-user', email='role-fixture@example.com', password='Synthetic-role-password-42!')
p = Practice.objects.create(name='Synthetic runtime role fixture')
UserProfile.objects.create(user=u, practice=p, role=UserProfile.Role.OWNER)
t = TherapistProfile.objects.create(user=u, practice=p)
c = Client.objects.create(practice=p, first_name='Synthetic', last_name='Role fixture')
c.first_name = 'Updated synthetic'
c.save()
n = SessionNote.objects.create(practice=p, client=c, therapist=t, content='Synthetic role content')
n.lock()
n.save()
AuditLog.objects.create(practice=p, actor=u, action='view', object_type='synthetic.RoleFixture')
for statement in ['UPDATE clinical_sessionnote SET is_locked=FALSE', 'DELETE FROM clinical_sessionnote']:
    try:
        with transaction.atomic(), connection.cursor() as cursor:
            cursor.execute(statement)
    except IntegrityError:
        pass
    else:
        raise AssertionError('Runtime role bypassed finalized-note protection')
browser = Browser()
assert browser.post('/login/', {'username': u.email, 'password': 'Synthetic-role-password-42!'}, secure=True).status_code == 302
assert browser.get('/dashboard/', secure=True).status_code == 200
assert browser.get('/clients/' + str(c.pk) + '/', secure=True).status_code == 200
assert browser.post('/logout/', secure=True).status_code == 302
assert '_auth_user_id' not in browser.session
print('Synthetic authenticated runtime and finalized-note guards passed.')
'''


if __name__ == '__main__':
    main()
