# Generated by Django 5.1.15 on 2026-09-17 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_rename_emergyency_contact_name_client_emergency_contact_name_and_more'),
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('appointment_type', models.CharField(choices=[('in_person', 'In Person'), ('video', 'Video Call'), ('phone', 'Phone Call')], default='video', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('external_calendar_provider', models.CharField(choices=[('none', 'None'), ('google', 'Google Calendar')], default='none', max_length=20)),
                ('external_calendar_id', models.CharField(blank=True, max_length=255)),
                ('external_event_id', models.CharField(blank=True, max_length=255)),
                ('external_event_url', models.URLField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('not_synced', 'Not Synced'), ('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='not_synced', max_length=20)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='practices.practice')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='practices.therapistprofile')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
