# Generated by Django 5.1.15 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_practiceworkinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='series_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
